---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/compiled-release

inputs:
  - name: director-state
  - name: bosh-cpi-release
  - name: bosh-cli

run:
  path: bosh-cpi-release/ci/bats/tasks/destroy-director.sh
