---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/azure-cpi-release

inputs:
  - name: bosh-cpi-release
  - name: bosh-cpi-dev-artifacts
  - name: version-semver
  - name: bosh-cli
outputs:
  - name: promoted
run:
  path: bosh-cpi-release/ci/tasks/promote-candidate.sh
params:
  S3_ACCESS_KEY_ID:     replace-me
  S3_SECRET_ACCESS_KEY: replace-me
