---
platform: linux
image: docker:///cloudfoundry/bosh-lite-ci

inputs:
  - name: bosh-softlayer-cpi
    path: gopath/src/github.com/cloudfoundry/bosh-softlayer-cpi

run:
  path: gopath/src/github.com/cloudfoundry/bosh-softlayer-cpi/bin/build